notifications:
  email:
    false

dist: trusty
sudo: required

language: c
compiler:
  - gcc

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
    - stage: app build
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install -qq build-essential autoconf automake libtool pkg-config
                       vpnc-scripts
                       gettext libproxy-dev libxml2-dev liblz4-1 liblz4-dev libstoken-dev liboath-dev
                       libgnutls28-dev # actually GnuTLS 3.2.11 ¯\_(ツ)_/¯
      script: 
        - ./autogen.sh
        - ./configure
        - make VERBOSE=1 version.c
        - make
        - make VERBOSE=1 -j4 check
    - stage: docker build
      services:
        - docker
      before_install:
        - docker build -t openconnect .
      script:
        - docker run openconnect "/openconnect/openconnect" "-V"
